// BitVault — inspired by CoinSwitch/CoinDCX (crypto fintech, ~800 people, Bangalore)
import type { CompanyProfile } from "../types.js";

const META = {
  companyKey: "bitvault",
  name: "BitVault",
  industry: "Crypto Fintech",
  stage: "Series C",
  size: "800 employees",
  city: "Bangalore",
  archetype: "B2C crypto fintech",
};

export const bitVaultPM: CompanyProfile = {
  ...META,
  id: "bitvault-pm",
  personaRole: "pm",
  persona: {
    name: "Kiran Reddy",
    role: "Product Manager — Activation & New User Growth",
    company: "BitVault",
    tenure: "1 year 9 months",
    reportsTo: "Sameer Jain (Head of Product)",
    toolStack: ["Slack", "Linear", "Notion", "Figma", "Mixpanel", "Clevertap", "Zoom", "Jira", "Confluence", "Google Sheets"],
    primaryCommsTools: ["Slack", "Linear"],
    invisibleComms: ["WhatsApp (compliance & legal quick loops)", "Telegram (crypto community monitoring)"],
    marketingTools: [],
    projects: [
      {
        name: "KYC Funnel Optimisation",
        codename: "Project Setu",
        status: "active",
        description: "KYC completion is at 67.2% — every point is worth ~₹8Cr ARR at current acquisition volumes. Biggest drop-offs: PAN OCR failure (18%) and selfie liveness check (9%). Working with CKYC integration to reduce step count from 7 to 4.",
        tools: ["Linear", "Mixpanel", "Figma", "Notion"],
        keyPeople: ["Sameer Jain", "Ananya Singh", "Riya Kapoor"],
      },
      {
        name: "First Trade Journey",
        codename: "Project Pehla",
        status: "active",
        description: "Only 34% of KYC-verified users make their first trade within 7 days. Redesigning the 'suggested first buy' surface with real-time price context and guided micro-investment flows.",
        tools: ["Figma", "Linear", "Mixpanel"],
        keyPeople: ["Riya Kapoor", "Ananya Singh"],
      },
      {
        name: "P2P Trading Surface",
        status: "blocked",
        description: "Blocked on RBI circular clarification — legal team says we can't ship until the July 31 guidance is published. Design and engineering are ready; just waiting on compliance green light.",
        tools: ["Notion"],
        keyPeople: ["Sameer Jain"],
      },
    ],
    collaborators: [
      { name: "Sameer Jain", role: "Head of Product", relationship: "manager", commsChannel: "Weekly 1:1 + Slack" },
      { name: "Ananya Singh", role: "Analytics Lead", relationship: "cross-functional", commsChannel: "Slack + Mixpanel shared dashboards" },
      { name: "Riya Kapoor", role: "Senior Designer", relationship: "peer", commsChannel: "Figma + Slack #design-crypto" },
      { name: "Dev Batra", role: "Engineering Lead, Onboarding", relationship: "peer", commsChannel: "Slack #onboarding-eng + Linear" },
      { name: "Pooja Sethi", role: "Compliance Manager", relationship: "cross-functional", commsChannel: "Email + ad-hoc Slack" },
    ],
    emailPatterns: [
      { subject: "[Linear] Dev assigned you #KYC-342: Integrate CKYC API v2 — replace current Karza flow", sender: "notify@linear.app", tool: "Linear" },
      { subject: "[Linear] #PEHLA-18 moved to Review: First trade recommendation engine — backend ready", sender: "notify@linear.app", tool: "Linear" },
      { subject: "[Linear] Sprint 28 review: 2 KYC tickets missed — need re-estimation", sender: "notify@linear.app", tool: "Linear" },
      { subject: "[Mixpanel] Funnel Alert: kyc_pan_upload→kyc_pan_verified drop-off exceeded 20% for 3 consecutive days", sender: "alerts@mixpanel.com", tool: "Mixpanel" },
      { subject: "[Mixpanel] Weekly retention digest: D7 first-trade retention 28.3% — down from 31.2% last cohort", sender: "digest@mixpanel.com", tool: "Mixpanel" },
      { subject: "[CleverTap] In-app message 'KYC Nudge — PAN pending' delivered to 127K users, 6.2% completion", sender: "noreply@clevertap.com", tool: "Clevertap" },
      { subject: "[Figma] Riya Kapoor shared 'KYC Redesign — Reduced Steps Flow' with you", sender: "noreply@figma.com", tool: "Figma" },
      { subject: "[Figma] Ananya Singh commented on 'First Trade Journey v3': 'Can we A/B test the price context card?'", sender: "noreply@figma.com", tool: "Figma" },
      { subject: "[Notion] Sameer Jain edited 'H2 Product Roadmap — Activation Track'", sender: "mail@mail.notion.so", tool: "Notion" },
      { subject: "[Confluence] Pooja Sethi updated 'P2P Trading — Compliance Requirements': RBI circular timeline added", sender: "confluence@atlassian.net", tool: "Confluence" },
      { subject: "Zoom Meeting Starting: Product Weekly — Wed 4:00 PM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "RE: P2P launch delay — legal review of July 31 RBI circular will take 2 more weeks", sender: "pooja.sethi@bitvault.in" },
      { subject: "RE: KYC selfie failure rate spiked to 12% — SDK update broke Android 11 devices", sender: "dev.batra@bitvault.in" },
      { subject: "IT: Your VPN certificate expires July 28 — renewal instructions attached", sender: "it@bitvault.in" },
      { subject: "Mandatory: SEBI KYC compliance refresher training due August 1 — all product employees", sender: "compliance@bitvault.in" },
      { subject: "Your June expense reimbursement of ₹8,800 has been processed", sender: "finance@bitvault.in" },
      { subject: "[Jira] PM-2841 updated: First Trade onboarding redesign — engineering estimate added by Dev Batra", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[Slack] You were mentioned in #onboarding-eng: 'KYC liveness check fix is in staging — Kiran, ready for review'", sender: "notifications@slack.com", tool: "Slack" },
      { subject: "CoinDesk Weekly: Regulatory roundup, institutional flows, and DeFi metrics — July 2024", sender: "newsletter@coindesk.com" },
    ],
    calendarPatterns: [
      { title: "Product Weekly", recurrence: "weekly", organizer: "Sameer Jain", attendees: ["all PMs", "design leads"], videoLink: "zoom.us" },
      { title: "1:1 with Sameer", recurrence: "weekly", organizer: "Sameer Jain", attendees: ["Kiran Reddy"], videoLink: "zoom.us" },
      { title: "KYC Sprint Review", recurrence: "biweekly", organizer: "Kiran Reddy", attendees: ["Dev Batra", "Riya Kapoor", "Ananya Singh"], videoLink: "meet.google.com" },
      { title: "Compliance Sync — P2P Status", recurrence: "weekly", organizer: "Pooja Sethi", attendees: ["Kiran Reddy", "Sameer Jain"], videoLink: "zoom.us" },
      { title: "BitVault All-Hands", recurrence: "monthly", organizer: "CEO office", attendees: ["all employees"], videoLink: "zoom.us" },
      { title: "KYC Regulatory Sync", recurrence: "weekly", organizer: "Pooja Sethi", attendees: ["Kiran Reddy", "Dev Batra", "Pooja Sethi"], videoLink: "meet.google.com" },
      { title: "Design Sprint — First Trade Onboarding v3", recurrence: "biweekly", organizer: "Riya Kapoor", attendees: ["Kiran Reddy", "Riya Kapoor", "Dev Batra"], videoLink: "meet.google.com" },
    ],
    weekNarrativeSeed: "KYC selfie failure spiked to 12% Monday — SDK broke on Android 11 devices, hotfix out by Tuesday noon. P2P is blocked on the July 31 RBI circular; engineering has been code-complete for 3 weeks and this is now pending a 2-week legal review minimum, which is pushing our Q3 activation targets. KYC completion is stuck at 67.2% vs our 72% July goal. First Trade A/B test: price context card is showing 3x more first trades vs control, but with n=720 per arm at Day 4 Ananya can't call it yet — we agreed to wait until Day 10.",
  },
};

export const bitVaultAnalyst: CompanyProfile = {
  ...META,
  id: "bitvault-analyst",
  personaRole: "analyst",
  persona: {
    name: "Ananya Singh",
    role: "Analytics Lead — User Growth & Trading",
    company: "BitVault",
    tenure: "2 years 5 months",
    reportsTo: "Rohit Arora (VP Data)",
    toolStack: ["Slack", "BigQuery", "dbt", "Redshift", "Looker", "Python", "Jupyter", "Airflow", "GitHub", "Jira", "Notion"],
    primaryCommsTools: ["Slack", "BigQuery"],
    invisibleComms: ["WhatsApp (crypto trading community research)", "Telegram (monitoring competitor announcements)"],
    marketingTools: [],
    projects: [
      {
        name: "Trading Retention Model",
        codename: "Project Compass",
        status: "active",
        description: "Predict which users will stop trading within 14 days using a gradient-boosted model on 38 features. Currently at AUC 0.81 — target 0.87 to ship to retention team for early intervention.",
        tools: ["BigQuery", "Python", "Jupyter", "GitHub"],
        keyPeople: ["Rohit Arora", "Kiran Reddy"],
      },
      {
        name: "KYC Funnel Attribution",
        status: "active",
        description: "Which acquisition channels produce users who complete KYC AND trade? Referral users are 2.3x more likely to trade in D7 vs Google UAC users, but the CAC is 5x higher. Informing channel mix decisions.",
        tools: ["BigQuery", "dbt", "Looker"],
        keyPeople: ["Vikram Iyer", "Kiran Reddy"],
      },
      {
        name: "Regulatory Reporting Automation",
        status: "planning",
        description: "Automate the monthly reports required by SEBI and RBI — currently takes the compliance team 3 days manually. Build dbt models and Airflow DAGs to generate them automatically.",
        tools: ["dbt", "Airflow", "BigQuery"],
        keyPeople: ["Rohit Arora"],
      },
    ],
    collaborators: [
      { name: "Rohit Arora", role: "VP Data", relationship: "manager", commsChannel: "Weekly 1:1 + Slack" },
      { name: "Kiran Reddy", role: "PM, Activation", relationship: "cross-functional", commsChannel: "Slack + shared Looker dashboards" },
      { name: "Vikram Iyer", role: "Marketing Lead", relationship: "cross-functional", commsChannel: "Slack + Looker shared reports" },
      { name: "Prateek Nanda", role: "Data Engineer", relationship: "peer", commsChannel: "GitHub + Slack #data-platform" },
      { name: "Sakshi Mehta", role: "Trading Product Analyst", relationship: "peer", commsChannel: "Slack + Notion shared workspace" },
    ],
    emailPatterns: [
      { subject: "[dbt Cloud] Job 'trading_retention_features_daily' failed — ValueError: timestamp column out of range", sender: "noreply@getdbt.com", tool: "dbt" },
      { subject: "[dbt Cloud] PR review requested: feat/kyc-attribution-model — adds channel_cohort_id join", sender: "noreply@getdbt.com", tool: "dbt" },
      { subject: "[Airflow] DAG 'sebi_monthly_report_etl' — scheduled for 2024-07-31, review trigger conditions", sender: "airflow-alerts@bitvault.in", tool: "Airflow" },
      { subject: "[Looker] 'Trading Cohort Dashboard' — weekly delivery to ananya.singh@bitvault.in", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "[Looker] Alert: D7 first-trade retention dropped below 28% — Ananya Singh notified", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "[GitHub] PR merged: fix/redshift-connection-timeout — Prateek Nanda", sender: "noreply@github.com", tool: "GitHub" },
      { subject: "[Jira] DATA-234 assigned to you: KYC completion rate by acquisition channel — needed for board pack", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[Notion] Kiran Reddy shared 'First Trade A/B Test — Request for Analysis' with you", sender: "mail@mail.notion.so", tool: "Notion" },
      { subject: "Zoom: Analytics Weekly — Tue 3:00 PM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "RE: Trading retention model — can we go to production at AUC 0.81 or wait for 0.87?", sender: "rohit.arora@bitvault.in" },
      { subject: "RE: First Trade A/B test — Kiran wants to call significance at Day 4, I'm not comfortable with n=2,100", sender: "sakshi.mehta@bitvault.in" },
      { subject: "IT: Your VPN certificate expires July 28 — renewal instructions attached", sender: "it@bitvault.in" },
      { subject: "Mandatory: SEBI KYC compliance refresher training due August 1 — all product employees", sender: "compliance@bitvault.in" },
      { subject: "Your June expense reimbursement of ₹6,400 has been processed", sender: "finance@bitvault.in" },
      { subject: "Towards Data Science weekly digest: gradient boosting, feature stores, ML model governance", sender: "noreply@towardsdatascience.com" },
    ],
    calendarPatterns: [
      { title: "Analytics Weekly", recurrence: "weekly", organizer: "Rohit Arora", attendees: ["Ananya Singh", "Prateek Nanda", "Sakshi Mehta"], videoLink: "zoom.us" },
      { title: "Data x PM Sync — KYC metrics", recurrence: "biweekly", organizer: "Kiran Reddy", attendees: ["Ananya Singh", "Kiran Reddy"], videoLink: "meet.google.com" },
      { title: "Model Review: Trading Retention", recurrence: "monthly", organizer: "Ananya Singh", attendees: ["Rohit Arora", "Prateek Nanda"], videoLink: "zoom.us" },
      { title: "BitVault Data Guild", recurrence: "monthly", organizer: "Rohit Arora", attendees: ["all data & analytics"], videoLink: "zoom.us" },
      { title: "Board Pack Data Preparation", recurrence: "monthly", organizer: "Rohit Arora", attendees: ["Ananya Singh", "Prateek Nanda"], videoLink: "zoom.us" },
      { title: "Crypto Analytics Deep Dive", recurrence: "biweekly", organizer: "Ananya Singh", attendees: ["Prateek Nanda", "Sakshi Mehta"], videoLink: "zoom.us" },
      { title: "A/B Test Readout — First Trade", recurrence: "weekly", organizer: "Kiran Reddy", attendees: ["Ananya Singh", "Kiran Reddy", "Riya Kapoor"], videoLink: "meet.google.com" },
      { title: "BitVault All-Hands", recurrence: "monthly", organizer: "CEO office", attendees: ["all employees"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "The trading retention model's training pipeline broke on Monday — a timestamp column out-of-range bug in dbt. Fixed by Tuesday but lost a day of training runs. Thursday was intense: Kiran wants to call the First Trade A/B test significant at Day 4 with n=2,100 users per arm — I pushed back because with crypto price volatility the effect size will swing wildly in a 4-day window. We agreed to wait until Day 10. Also: the board pack is due next Monday and I still need the KYC completion by acquisition channel breakdown — Vikram is asking for it too for his CAC analysis.",
  },
};

export const bitVaultMarketing: CompanyProfile = {
  ...META,
  id: "bitvault-marketing",
  personaRole: "marketing",
  persona: {
    name: "Vikram Iyer",
    role: "Growth Marketing Lead",
    company: "BitVault",
    tenure: "2 years",
    reportsTo: "Nita Sharma (CMO)",
    toolStack: ["Slack", "Google Ads", "Meta Ads", "Google Analytics", "AppsFlyer", "CleverTap", "Looker", "Zoom", "Jira", "Canva", "Notion"],
    primaryCommsTools: ["Slack", "Google Ads"],
    invisibleComms: ["WhatsApp (crypto influencer coordination)", "Telegram (community management)"],
    marketingTools: ["Google Ads", "Meta Ads", "Google Analytics", "AppsFlyer"],
    projects: [
      {
        name: "Referral Programme v3",
        codename: "Project Mitra",
        status: "active",
        description: "Current referral: 18.7% conversion, ₹340 CAC (vs ₹1,800 paid). Redesigning incentive structure — moving from ₹100 flat to 5% of referee's first trade up to ₹500. Hypothesis: trade-linked reward attracts better LTV users.",
        tools: ["Google Analytics", "AppsFlyer", "Looker"],
        keyPeople: ["Nita Sharma", "Kiran Reddy", "Ananya Singh"],
      },
      {
        name: "Bull Market Acquisition Push",
        status: "active",
        description: "BTC crossed ₹55L — historic spike in search intent for 'buy bitcoin india'. Activating performance budget: +₹2Cr incremental Google Ads in the next 7 days to capture intent while it's hot.",
        tools: ["Google Ads", "Meta Ads", "AppsFlyer"],
        keyPeople: ["Nita Sharma"],
      },
      {
        name: "Creator Partnership Programme",
        status: "planning",
        description: "Work with 15 personal finance creators (500K-5M subscribers) for authentic crypto education content. Target: 40K installs at ₹280 CAC by Q4.",
        tools: ["Notion", "Canva"],
        keyPeople: ["Nita Sharma"],
      },
    ],
    collaborators: [
      { name: "Nita Sharma", role: "CMO", relationship: "manager", commsChannel: "Weekly 1:1 + Slack" },
      { name: "Kiran Reddy", role: "PM, Activation", relationship: "cross-functional", commsChannel: "Slack + monthly alignment" },
      { name: "Ananya Singh", role: "Analytics Lead", relationship: "cross-functional", commsChannel: "Slack + Looker shared dashboards" },
      { name: "Arun Bose", role: "SEO & Content Lead", relationship: "peer", commsChannel: "Slack #growth-content + weekly" },
      { name: "Meena Iyer", role: "Influencer Marketing Manager", relationship: "peer", commsChannel: "Slack + Notion shared workspace" },
    ],
    emailPatterns: [
      { subject: "[Google Ads] Alert: Campaign 'India_Crypto_Brand_Search' budget depleted — daily ₹80,000 cap reached at 2:14 PM", sender: "googleads-noreply@google.com", tool: "Google Ads" },
      { subject: "[Google Ads] Smart Bidding recommendation: Increase Target CPA to ₹420 — estimated +34% conversions", sender: "googleads-noreply@google.com", tool: "Google Ads" },
      { subject: "[Google Ads] Weekly performance: Install campaigns — 14,200 installs, CPI ₹127, blended CPA ₹1,840", sender: "googleads-noreply@google.com", tool: "Google Ads" },
      { subject: "[Meta for Business] Your ad set 'Crypto_Beginners_LA_25-35' delivery limited — audience too small after iOS 14 constraints", sender: "advertiser-noreply@meta.com", tool: "Meta Ads" },
      { subject: "[Meta Business Manager] 'Lookalike_Portfolio_Users_3pct' reached ₹1.5L threshold — review spend", sender: "noreply@facebookmail.com", tool: "Meta Ads" },
      { subject: "[AppsFlyer] Install attribution — July Week 2: Google UAC 44%, Organic 21%, Referral 22%, Meta 13%", sender: "noreply@appsflyer.com", tool: "AppsFlyer" },
      { subject: "[AppsFlyer] Fraud protection: Blocked 2,400 installs from publisher ID 92411 this week", sender: "noreply@appsflyer.com", tool: "AppsFlyer" },
      { subject: "[CleverTap] Push campaign 'Bull Market Alert — BTC hits ₹55L' CTR: 11.2% (best this quarter)", sender: "noreply@clevertap.com", tool: "CleverTap" },
      { subject: "[Google Analytics] Organic search spike: 'bitcoin price in india' up 340% WoW — 82K sessions this week", sender: "noreply@google.com", tool: "Google Analytics" },
      { subject: "[Looker] 'Growth Marketing CAC Dashboard' — Vikram Iyer, weekly delivery", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "Zoom: Growth Marketing Weekly — Mon 10:00 AM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "[Jira] GROW-892 assigned to you: Set up referral v3 tracking in AppsFlyer — custom event schema needed", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "RE: Bull market campaign — Nita approved incremental ₹2Cr spend, needs to go live by tonight", sender: "nita.sharma@bitvault.in" },
      { subject: "RE: Creator programme shortlist — 15 creators reviewed, Arun recommends top 5 for Q3 kickoff", sender: "meena.iyer@bitvault.in" },
      { subject: "IT: Your VPN certificate expires July 28 — renewal instructions attached", sender: "it@bitvault.in" },
      { subject: "Mandatory: SEBI KYC compliance refresher training due August 1 — all product employees", sender: "compliance@bitvault.in" },
      { subject: "Your June expense reimbursement of ₹11,200 has been processed", sender: "finance@bitvault.in" },
      { subject: "MMA India: Performance marketing in crypto — install cost benchmarks and attribution challenges", sender: "insights@mmaglobal.com" },
    ],
    calendarPatterns: [
      { title: "Growth Marketing Weekly", recurrence: "weekly", organizer: "Nita Sharma", attendees: ["Vikram Iyer", "Arun Bose", "Meena Iyer"], videoLink: "zoom.us" },
      { title: "1:1 with Nita", recurrence: "biweekly", organizer: "Nita Sharma", attendees: ["Vikram Iyer"], videoLink: "zoom.us" },
      { title: "Referral v3 Alignment — Product x Marketing", recurrence: "weekly", organizer: "Kiran Reddy", attendees: ["Vikram Iyer", "Kiran Reddy", "Ananya Singh"], videoLink: "meet.google.com" },
      { title: "CMO Weekly Briefing", recurrence: "weekly", organizer: "Nita Sharma", attendees: ["all marketing leads"], videoLink: "zoom.us" },
      { title: "Creator Programme Planning", recurrence: "biweekly", organizer: "Vikram Iyer", attendees: ["Vikram Iyer", "Meena Iyer", "Arun Bose"], videoLink: "meet.google.com" },
      { title: "CleverTap Campaign Performance Review", recurrence: "biweekly", organizer: "Vikram Iyer", attendees: ["Vikram Iyer", "Meena Iyer"], videoLink: "zoom.us" },
      { title: "BitVault Marketing All-Hands", recurrence: "monthly", organizer: "Nita Sharma", attendees: ["all marketing"], videoLink: "zoom.us" },
      { title: "Influencer & Creator Monthly Review", recurrence: "monthly", organizer: "Vikram Iyer", attendees: ["Arun Bose", "Meena Iyer", "Vikram Iyer"], videoLink: "meet.google.com" },
    ],
    weekNarrativeSeed: "BTC crossed ₹55L Tuesday so I scrambled to get Nita's approval for a ₹2Cr incremental Google Ads spend — campaigns live by midnight. CleverTap push CTR hit 11.2% for the bull market alert, best this quarter. The downside: Meta is blocking reach on the crypto vertical again due to financial services policy — 18% of planned impressions couldn't be delivered. Referral v3 launch is pending App Store review which Arun says could take 10 days. Alignment with Kiran and Ananya was good: trade-linked incentive is testable without a platform rebuild, which was my main blocker.",
  },
};
