// SwiftShip — inspired by Delhivery/Shadowfax (logistics tech, ~2,500 employees, Gurgaon)
import type { CompanyProfile } from "../types.js";

const META = {
  companyKey: "swiftship",
  name: "SwiftShip",
  industry: "Logistics Tech",
  stage: "Post-IPO / Series D",
  size: "2,500 tech & ops employees",
  city: "Gurgaon",
  archetype: "B2B logistics tech",
};

export const swiftShipPM: CompanyProfile = {
  ...META,
  id: "swiftship-pm",
  personaRole: "pm",
  persona: {
    name: "Ravi Menon",
    role: "Product Manager — Last Mile Delivery App",
    company: "SwiftShip",
    tenure: "2 years 1 month",
    reportsTo: "Anjali Shah (Head of Product, Last Mile)",
    toolStack: ["Slack", "Jira", "Confluence", "Figma", "Mixpanel", "Looker", "Zoom", "Notion", "PagerDuty", "Firebase"],
    primaryCommsTools: ["Slack", "Jira"],
    invisibleComms: ["WhatsApp (delivery partner escalations)", "phone calls with hub managers"],
    marketingTools: [],
    projects: [
      {
        name: "Route Optimisation v3",
        codename: "Project Vayu",
        status: "active",
        description: "New ML-based route engine reduces delivery partner travel by 18% on pilot in Pune. Full rollout blocked by map data licensing negotiation — MapmyIndia contract renewal is 3 weeks out.",
        tools: ["Jira", "Looker", "Mixpanel", "Firebase"],
        keyPeople: ["Anjali Shah", "Data Science team", "ops"],
      },
      {
        name: "Delivery Partner Earnings Transparency",
        codename: "Project Sparsh",
        status: "active",
        description: "Delivery partners churn at 22%/month; top reason in exit surveys is earnings confusion. Building a real-time earnings breakdown in the partner app: base pay + surge + bonuses + deductions, per trip.",
        tools: ["Figma", "Jira", "Firebase"],
        keyPeople: ["Kavitha Krishnan", "partner ops team"],
      },
      {
        name: "Smart Re-delivery Scheduling",
        status: "planning",
        description: "First-attempt delivery success is 84.3%. If we can predict when the customer is home (based on past delivery history + consent-based location), we can boost this to 92%. Needs privacy framework first.",
        tools: ["Notion", "Jira"],
        keyPeople: ["Anjali Shah", "legal"],
      },
    ],
    collaborators: [
      { name: "Anjali Shah", role: "Head of Product, Last Mile", relationship: "manager", commsChannel: "Weekly 1:1 + Slack" },
      { name: "Kavitha Krishnan", role: "Analytics Manager, Operations", relationship: "cross-functional", commsChannel: "Slack + shared Looker dashboards" },
      { name: "Suresh Yadav", role: "Engineering Lead, Partner App", relationship: "peer", commsChannel: "Slack #partner-app-eng + Jira" },
      { name: "Priyanka Desai", role: "Operations Partner Lead", relationship: "cross-functional", commsChannel: "Slack + bi-weekly ops sync" },
      { name: "Manish Agarwal", role: "Data Science Lead, Routing", relationship: "cross-functional", commsChannel: "Slack + monthly routing review" },
    ],
    emailPatterns: [
      { subject: "[Jira] PARTNER-892 assigned to you: Build earnings breakdown screen — base + surge + bonus per trip", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[Jira] VAYU-34: Route optimisation rollout blocked — MapmyIndia contract under legal review", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[PagerDuty] CRITICAL: partner_app_crash_rate 8.3% on Android 12 — affecting 4,200 active deliveries", sender: "noreply@pagerduty.com", tool: "PagerDuty" },
      { subject: "[Mixpanel] Alert: delivery_partner_app_session_length dropped 22% — possible UX regression", sender: "alerts@mixpanel.com", tool: "Mixpanel" },
      { subject: "[Firebase] A/B test 'Earnings Transparency v1' has 10,000 users — 7 days remaining", sender: "noreply@firebase.google.com", tool: "Firebase" },
      { subject: "[Figma] Suresh Yadav commented on 'Earnings Breakdown — Mobile Screen v4': 'Surge display needs localisation'", sender: "noreply@figma.com", tool: "Figma" },
      { subject: "[Confluence] Manish Agarwal updated 'Route Optimisation v3 — ML Model Architecture'", sender: "confluence@atlassian.net", tool: "Confluence" },
      { subject: "[Looker] 'Last Mile Operations Dashboard' — Ravi Menon, daily delivery report ready", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "Zoom: Last Mile Product Weekly — Mon 3:00 PM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "RE: Project Vayu rollout — legal says MapmyIndia contract will close by July 28", sender: "anjali.shah@swiftship.in" },
      { subject: "RE: Delivery partner churn — Priyanka's team ran exit surveys: 41% cite earnings confusion as #1 reason", sender: "priyanka.desai@swiftship.in" },
    ],
    calendarPatterns: [
      { title: "Last Mile Product Weekly", recurrence: "weekly", organizer: "Anjali Shah", attendees: ["all last mile PMs"], videoLink: "zoom.us" },
      { title: "1:1 with Anjali", recurrence: "weekly", organizer: "Anjali Shah", attendees: ["Ravi Menon"], videoLink: "zoom.us" },
      { title: "Partner App Sprint Review", recurrence: "biweekly", organizer: "Ravi Menon", attendees: ["Suresh Yadav", "Kavitha Krishnan", "Priyanka Desai"], videoLink: "zoom.us" },
      { title: "Routing Model Review", recurrence: "monthly", organizer: "Manish Agarwal", attendees: ["Ravi Menon", "Anjali Shah", "data science"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "Partner app crashed on Android 12 Monday morning — 8.3% crash rate affecting active deliveries, Suresh had a fix in 2 hours but we're still getting hub manager calls via WhatsApp. The exit survey data Priyanka shared is damning: 41% of churning partners cite earnings confusion. That validates Project Sparsh but also tells me we need to ship faster. The MapmyIndia contract is still in legal — Anjali says July 28 which means Project Vayu rollout is 2 weeks behind my original Q3 plan. Firebase A/B test for earnings transparency is running but it's too early to read.",
  },
};

export const swiftShipAnalyst: CompanyProfile = {
  ...META,
  id: "swiftship-analyst",
  personaRole: "analyst",
  persona: {
    name: "Kavitha Krishnan",
    role: "Analytics Manager — Operations & SLA",
    company: "SwiftShip",
    tenure: "3 years",
    reportsTo: "Deepak Joshi (VP Operations)",
    toolStack: ["Slack", "BigQuery", "dbt", "Looker", "Python", "Jupyter", "Airflow", "GitHub", "Jira", "Tableau", "Zoom"],
    primaryCommsTools: ["Slack", "Looker"],
    invisibleComms: ["WhatsApp (hub manager network)", "phone calls with regional ops heads"],
    marketingTools: [],
    projects: [
      {
        name: "SLA Breach Prediction",
        codename: "Project Samay",
        status: "active",
        description: "Predict which shipments will breach their delivery SLA 12 hours in advance, enabling proactive intervention. Model at AUC 0.83 in staging. If we prevent 20% of breaches, saves ₹2.1Cr/month in SLA penalties.",
        tools: ["BigQuery", "Python", "Airflow"],
        keyPeople: ["Deepak Joshi", "Ravi Menon", "hub ops"],
      },
      {
        name: "Hub Efficiency Dashboard",
        status: "active",
        description: "Real-time ops metrics for 180 hubs: throughput, error rate, delay reasons, partner utilisation. Replacing the Excel-based manual reporting that hub managers update daily.",
        tools: ["BigQuery", "dbt", "Looker"],
        keyPeople: ["regional ops leads", "Deepak Joshi"],
      },
      {
        name: "Delivery Partner Segmentation",
        status: "planning",
        description: "Segment delivery partners by reliability, availability patterns, area expertise, and complaint rate. Power smarter assignment algorithms and the partner tier programme that product is building.",
        tools: ["BigQuery", "Python", "dbt"],
        keyPeople: ["Ravi Menon", "Manish Agarwal"],
      },
    ],
    collaborators: [
      { name: "Deepak Joshi", role: "VP Operations", relationship: "manager", commsChannel: "Daily ops review + Slack" },
      { name: "Ravi Menon", role: "PM, Last Mile App", relationship: "cross-functional", commsChannel: "Slack + bi-weekly" },
      { name: "Manish Agarwal", role: "Data Science Lead, Routing", relationship: "peer", commsChannel: "Slack + model collaboration" },
      { name: "Neha Chandra", role: "Data Engineer", relationship: "peer", commsChannel: "GitHub + Slack #data-platform" },
      { name: "Rahul Ops lead", role: "North Region Ops Lead", relationship: "cross-functional", commsChannel: "Looker shared dashboards + Slack" },
    ],
    emailPatterns: [
      { subject: "[Airflow] DAG 'sla_breach_prediction_scoring' — completed: 2.1M shipments scored in 4m 32s", sender: "airflow-alerts@swiftship.in", tool: "Airflow" },
      { subject: "[Airflow] DAG 'hub_efficiency_etl_hourly' failed — Kafka consumer lag exceeded threshold", sender: "airflow-alerts@swiftship.in", tool: "Airflow" },
      { subject: "[Looker] Alert: Delhi hub average processing time crossed 4.2 hours (threshold: 3.5)", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "[Looker] 'Operations Command Dashboard' — Kavitha Krishnan, 6 AM daily delivery", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "[dbt Cloud] 'mart_hub_daily_metrics' — 1 test failed: accepted_values on delay_reason_code", sender: "noreply@getdbt.com", tool: "dbt" },
      { subject: "[GitHub] PR merged: feat/sla-prediction-feature-engineering — Neha Chandra", sender: "noreply@github.com", tool: "GitHub" },
      { subject: "[Jira] OPS-2341 assigned to you: Hub efficiency dashboard — add real-time partner utilisation metric", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "Zoom: Operations Analytics Weekly — Wed 10:00 AM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "RE: SLA breach model — Deepak wants pilot with Delhi + Mumbai hubs by end of July", sender: "manish.agarwal@swiftship.in" },
      { subject: "RE: Hub efficiency dashboard — North region ops leads want it in Hindi UI, is that feasible?", sender: "rahul.ops@swiftship.in" },
    ],
    calendarPatterns: [
      { title: "Operations Analytics Weekly", recurrence: "weekly", organizer: "Deepak Joshi", attendees: ["Kavitha Krishnan", "Manish Agarwal", "Neha Chandra"], videoLink: "zoom.us" },
      { title: "Daily Ops Review", recurrence: "daily", organizer: "Deepak Joshi", attendees: ["ops leads + analytics"], videoLink: "meet.google.com" },
      { title: "Hub Dashboard Review with Regions", recurrence: "monthly", organizer: "Kavitha Krishnan", attendees: ["all regional ops leads"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "SLA prediction model is staging-complete at AUC 0.83 but Deepak wants a Delhi + Mumbai pilot by end of July — that's 2 weeks less than I planned. The Airflow hub ETL failed Tuesday due to Kafka consumer lag; our ops team had to fall back to manual checks for 3 hours which made the Delhi hub alert miss. North region is asking for the hub dashboard in Hindi — I don't have the bandwidth but I'm also not in a position to say no to Deepak's ops leads. Partner segmentation needs to be prioritised soon or Ravi can't build the tier programme on time.",
  },
};

export const swiftShipMarketing: CompanyProfile = {
  ...META,
  id: "swiftship-marketing",
  personaRole: "marketing",
  persona: {
    name: "Shubham Gupta",
    role: "Growth Manager — Enterprise Client Acquisition",
    company: "SwiftShip",
    tenure: "1 year 8 months",
    reportsTo: "Priti Rajan (VP Sales & Marketing)",
    toolStack: ["Slack", "Salesforce", "HubSpot", "LinkedIn Ads", "Google Analytics", "Outreach", "Zoom", "Jira", "Notion", "Google Ads"],
    primaryCommsTools: ["Slack", "Salesforce"],
    invisibleComms: ["WhatsApp (enterprise prospect coordination)", "phone calls with logistics heads at target accounts"],
    marketingTools: ["LinkedIn Ads", "Google Analytics", "Google Ads"],
    projects: [
      {
        name: "D2C Brand Acquisition — Q3",
        status: "active",
        description: "Target: 8 new enterprise D2C clients (>2,000 shipments/day) by Q3-end. Pipeline: 22 accounts in Salesforce at various stages. Current conversion from demo to contract: 31%. Target: 45%.",
        tools: ["Salesforce", "HubSpot", "LinkedIn Ads", "Outreach"],
        keyPeople: ["Priti Rajan", "enterprise sales team"],
      },
      {
        name: "Content & Thought Leadership",
        status: "active",
        description: "Logistics industry content: 'State of D2C Fulfilment 2024' report, case studies from Mamaearth and Bewakoof implementations. Target: 400 qualified MQLs from content by Q3.",
        tools: ["HubSpot", "Google Analytics", "LinkedIn Ads"],
        keyPeople: ["content team"],
      },
      {
        name: "Partner Referral Programme",
        status: "planning",
        description: "WMS and OMS vendors (Vinculum, Unicommerce) refer clients to SwiftShip for fulfilment — revenue share model. Potentially 15 new enterprise clients/quarter at near-zero CAC.",
        tools: ["Salesforce", "Notion"],
        keyPeople: ["Priti Rajan", "partner team"],
      },
    ],
    collaborators: [
      { name: "Priti Rajan", role: "VP Sales & Marketing", relationship: "manager", commsChannel: "Weekly 1:1 + Slack" },
      { name: "Arun enterprise lead", role: "Enterprise Sales Lead", relationship: "peer", commsChannel: "Salesforce + Slack #enterprise-sales" },
      { name: "Neha content", role: "Content Lead", relationship: "peer", commsChannel: "Slack + HubSpot shared workspace" },
      { name: "Kavitha Krishnan", role: "Analytics Manager", relationship: "cross-functional", commsChannel: "Slack + monthly operational metrics sharing" },
      { name: "D2C client success", role: "Client Success Manager", relationship: "cross-functional", commsChannel: "Salesforce + weekly deal reviews" },
    ],
    emailPatterns: [
      { subject: "[LinkedIn Ads] Campaign 'SwiftShip_D2C_Logistics_IN' — 2,400 impressions, 0.6% CTR, 14 website visits", sender: "noreply@linkedin.com", tool: "LinkedIn Ads" },
      { subject: "[LinkedIn Ads] Lead gen form 'Q3 Fulfilment Benchmark Report' — 28 new leads this week", sender: "noreply@linkedin.com", tool: "LinkedIn Ads" },
      { subject: "[Salesforce] Opportunity 'Mamaearth Expansion — Phase 2' moved to Negotiation stage", sender: "salesforce@salesforce.com", tool: "Salesforce" },
      { subject: "[Salesforce] 7 opportunities have had no activity in 21+ days — pipeline health alert", sender: "salesforce@salesforce.com", tool: "Salesforce" },
      { subject: "[HubSpot] Contact 'Head of Logistics, Nykaa' opened your 'State of D2C Fulfilment 2024' email 3 times", sender: "notifications@hubspot.com", tool: "HubSpot" },
      { subject: "[HubSpot] 'D2C Logistics Decision Maker Nurture' — Step 3 email: 18.2% open rate, 4.1% click", sender: "noreply@hubspot.com", tool: "HubSpot" },
      { subject: "[Outreach] Sequence 'Enterprise D2C Q3' — 14 prospects completed step 3, 6 opened but didn't reply", sender: "noreply@outreach.io", tool: "Outreach" },
      { subject: "[Google Analytics] Blog: 'How D2C brands reduce RTO from 18% to 9%' — 2,400 organic sessions this week", sender: "noreply@google.com", tool: "Google Analytics" },
      { subject: "[Google Ads] Campaign 'Logistics Software Decision Maker India' — 340 clicks, CPC ₹88", sender: "googleads-noreply@google.com", tool: "Google Ads" },
      { subject: "Zoom: Enterprise Sales Weekly — Fri 3:00 PM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "RE: Mamaearth negotiation — they want an SLA guarantee for 96% on-time delivery or penalty clause", sender: "arun.enterprise@swiftship.in" },
      { subject: "RE: Nykaa Head of Logistics opened the report 3 times — should we call?", sender: "priti.rajan@swiftship.in" },
    ],
    calendarPatterns: [
      { title: "Enterprise Sales Weekly", recurrence: "weekly", organizer: "Priti Rajan", attendees: ["Shubham Gupta", "Arun enterprise lead", "sales team"], videoLink: "zoom.us" },
      { title: "Deal Review — Enterprise Pipeline", recurrence: "weekly", organizer: "Shubham Gupta", attendees: ["Priti Rajan", "Arun enterprise lead"], videoLink: "zoom.us" },
      { title: "Content x Demand Gen Monthly", recurrence: "monthly", organizer: "Shubham Gupta", attendees: ["Neha content", "Shubham Gupta"], videoLink: "meet.google.com" },
    ],
    weekNarrativeSeed: "Mamaearth Phase 2 expansion moved to negotiation on Monday — they're asking for a 96% on-time SLA guarantee with a penalty clause which is above our current 94.2% platform average. Priti and I are deciding how hard to push back. The Nykaa Head of Logistics has opened our fulfilment report 3 times without replying — classic high-intent signal, calling her Friday. Pipeline has 7 stale deals which I need to clean before Monday's review. The LinkedIn lead gen form from the D2C benchmark report is performing well: 28 leads this week, which is our best organic week this quarter.",
  },
};
