// QuickCart — inspired by Flipkart (ecommerce, ~15,000 employees, Bangalore)
import type { CompanyProfile } from "../types.js";

const META = {
  companyKey: "quickcart",
  name: "QuickCart",
  industry: "Ecommerce",
  stage: "Late Stage / Walmart subsidiary",
  size: "15,000 employees",
  city: "Bangalore",
  archetype: "B2C ecommerce",
};

export const quickCartPM: CompanyProfile = {
  ...META,
  id: "quickcart-pm",
  personaRole: "pm",
  persona: {
    name: "Meera Nair",
    role: "Senior Product Manager — Seller Platform",
    company: "QuickCart",
    tenure: "3 years 6 months",
    reportsTo: "Varun Khanna (Director of Product, Seller Platform)",
    toolStack: ["Slack", "Jira", "Confluence", "Figma", "Amplitude", "Looker", "Zoom", "Notion", "ServiceNow", "GitHub"],
    primaryCommsTools: ["Slack", "Jira"],
    invisibleComms: ["WhatsApp (seller success team escalations)", "seller helpline call recordings"],
    marketingTools: [],
    projects: [
      {
        name: "Seller Onboarding Automation",
        codename: "Project Vistaar",
        status: "active",
        description: "Reduce time-to-first-listing from 11 days to <3 by automating GST verification, bank account validation, and catalogue template selection. Currently 8,200 new sellers/month and we're losing 40% during the 11-day wait.",
        tools: ["Jira", "Amplitude", "Figma", "Confluence"],
        keyPeople: ["Varun Khanna", "Aisha Rao", "Dev Menon"],
      },
      {
        name: "Catalogue Quality Score",
        codename: "Project Suchita",
        status: "active",
        description: "ML model to score product listing quality — image clarity, description completeness, pricing competitiveness. Sellers in top quartile have 3.4x conversion vs bottom quartile. Building a seller-facing scorecard.",
        tools: ["Amplitude", "Looker", "Confluence"],
        keyPeople: ["Rahul Bose", "Aisha Rao"],
      },
      {
        name: "Seller Payments Transparency",
        status: "blocked",
        description: "Sellers can't reconcile their payments — the ledger UI is 4 years old. Blocked because the payments team's Kafka migration takes priority and shares the same backend team.",
        tools: ["Jira"],
        keyPeople: ["Varun Khanna", "payments team"],
      },
    ],
    collaborators: [
      { name: "Varun Khanna", role: "Director of Product, Seller Platform", relationship: "manager", commsChannel: "Weekly 1:1 + Slack" },
      { name: "Aisha Rao", role: "Senior Designer", relationship: "peer", commsChannel: "Figma + Slack #seller-design" },
      { name: "Dev Menon", role: "Engineering Lead, Seller Onboarding", relationship: "peer", commsChannel: "Slack #seller-eng + Jira" },
      { name: "Rahul Bose", role: "Data Science Lead", relationship: "cross-functional", commsChannel: "Slack + quarterly model review" },
      { name: "Sonal Gupta", role: "Seller Success Manager", relationship: "cross-functional", commsChannel: "Slack + bi-weekly seller feedback session" },
    ],
    emailPatterns: [
      { subject: "[Jira] SELL-2341 assigned to you: Automate GST verification via Karza API integration", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[Jira] SELL-2389: Seller onboarding drop-off at bank verification step — Varun Khanna escalated to P1", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[Jira] SELL-1892 blocked: Seller Payments Transparency — dependency on payments team Kafka migration", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[Amplitude] Funnel Alert: seller_gstin_verified→first_listing drop-off increased 6pp this week", sender: "alerts@amplitude.com", tool: "Amplitude" },
      { subject: "[Amplitude] New experiment live: 'Simplified Catalogue Template v2' — targeting 2,000 electronics sellers", sender: "noreply@amplitude.com", tool: "Amplitude" },
      { subject: "[Figma] Aisha Rao shared 'Seller Onboarding Redesign — GST Step v3' with you", sender: "noreply@figma.com", tool: "Figma" },
      { subject: "[Confluence] Dev Menon updated 'Seller Onboarding — Karza API Integration Spec'", sender: "confluence@atlassian.net", tool: "Confluence" },
      { subject: "[Looker] 'Seller Health Dashboard' — weekly report: time-to-first-listing at 8.3 days (prev 10.2)", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "[ServiceNow] Incident INC0089234: Seller catalogue upload service — 503 errors for 23 minutes", sender: "noreply@service-now.com", tool: "ServiceNow" },
      { subject: "Zoom: Seller Platform Weekly — Thu 2:00 PM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "RE: Project Vistaar — Karza API rate limits will affect 12% of sellers during peak; need fallback design", sender: "dev.menon@quickcart.in" },
      { subject: "RE: Seller feedback session — 7 sellers cited payment reconciliation as #1 pain, even before onboarding", sender: "sonal.gupta@quickcart.in" },
      { subject: "[GitHub] Meera Nair, PR #3421 'seller-gstin-validation' has passed all CI checks", sender: "noreply@github.com", tool: "GitHub" },
      { subject: "IT: Please verify your active Microsoft 365 licences in the IT portal before July 15", sender: "it@quickcart.in" },
      { subject: "QuickCart All-Hands July 2024 — CEO Q3 update, BBD preview, recording on intranet", sender: "allhands@quickcart.in" },
      { subject: "Your June expense claim of ₹16,500 (BBD planning travel) has been approved", sender: "finance@quickcart.in" },
      { subject: "Ecommerce Product Leaders India: seller growth, marketplace monetisation, and app commerce", sender: "digest@ecommercepli.in" },
    ],
    calendarPatterns: [
      { title: "Seller Platform Weekly", recurrence: "weekly", organizer: "Varun Khanna", attendees: ["all seller PMs"], videoLink: "zoom.us" },
      { title: "1:1 with Varun", recurrence: "weekly", organizer: "Varun Khanna", attendees: ["Meera Nair"], videoLink: "zoom.us" },
      { title: "Project Vistaar Sprint Review", recurrence: "biweekly", organizer: "Meera Nair", attendees: ["Dev Menon", "Aisha Rao", "Sonal Gupta"], videoLink: "zoom.us" },
      { title: "Seller Feedback Listening Session", recurrence: "biweekly", organizer: "Sonal Gupta", attendees: ["Meera Nair", "Aisha Rao", "5 sellers"], videoLink: "zoom.us" },
      { title: "QuickCart All-Hands", recurrence: "monthly", organizer: "CEO office", attendees: ["all employees"], videoLink: "zoom.us" },
      { title: "Seller Experience Council", recurrence: "biweekly", organizer: "Varun Khanna", attendees: ["seller PMs", "seller success", "ops leads"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "Dev flagged a Karza API rate limit issue that'll hit 12% of sellers during Big Billion Days volume — we need a graceful fallback to manual verification for when the API throttles. Spent Tuesday-Wednesday designing the fallback UX with Aisha. The seller feedback session on Thursday was eye-opening: 7 sellers, and ALL of them rated payment reconciliation as their #1 pain point — even more than onboarding. That's awkward because Seller Payments is blocked by the payments team's Kafka migration. Varun asked me to build a business case for de-prioritising the Kafka work in Q4 so we can unblock this.",
  },
};

export const quickCartAnalyst: CompanyProfile = {
  ...META,
  id: "quickcart-analyst",
  personaRole: "analyst",
  persona: {
    name: "Arjun Shah",
    role: "Growth Analyst — Seller GMV & Category Performance",
    company: "QuickCart",
    tenure: "2 years",
    reportsTo: "Pooja Krishnan (Head of Analytics, Marketplace)",
    toolStack: ["Slack", "Hive", "Spark", "Tableau", "dbt", "Airflow", "Python", "GitHub", "Jira", "Confluence", "Zoom"],
    primaryCommsTools: ["Slack", "Tableau"],
    invisibleComms: ["WhatsApp (category team quick questions)"],
    marketingTools: [],
    projects: [
      {
        name: "Big Billion Days Pre-analysis",
        codename: "Project Dhamaka",
        status: "active",
        description: "Pre-BBD seller and category readiness analysis: which categories are undersupplied, which sellers need inventory nudges, and where is the price competitiveness gap vs Amazon. Due to category heads in 3 weeks.",
        tools: ["Hive", "Spark", "Tableau", "dbt"],
        keyPeople: ["Pooja Krishnan", "category heads"],
      },
      {
        name: "Seller Tier Model Revamp",
        status: "active",
        description: "Current Gold/Silver/Bronze tier model hasn't been recalibrated in 2 years. Building a new multi-dimensional score: GMV, catalogue quality, SLA compliance, return rate, customer rating. Affects 1.2M sellers.",
        tools: ["Hive", "Python", "Tableau"],
        keyPeople: ["Meera Nair", "Pooja Krishnan"],
      },
      {
        name: "Return Rate Attribution",
        status: "planning",
        description: "8.3% blended return rate is hurting unit economics. Need to attribute returns by: seller quality, logistics partner, product category, and customer return behaviour pattern. Will inform the seller penalty scoring.",
        tools: ["Hive", "dbt", "Tableau"],
        keyPeople: ["Pooja Krishnan"],
      },
    ],
    collaborators: [
      { name: "Pooja Krishnan", role: "Head of Analytics, Marketplace", relationship: "manager", commsChannel: "Daily async + Slack" },
      { name: "Meera Nair", role: "Senior PM, Seller Platform", relationship: "cross-functional", commsChannel: "Slack + data requests via Jira" },
      { name: "Neha Singh", role: "Data Engineer", relationship: "peer", commsChannel: "GitHub + Slack #data-eng" },
      { name: "Vikram Das", role: "Category Analytics Lead (Electronics)", relationship: "peer", commsChannel: "Slack + shared Tableau workbooks" },
      { name: "Riya Malhotra", role: "Category Analytics Lead (Fashion)", relationship: "peer", commsChannel: "Slack + monthly category review" },
    ],
    emailPatterns: [
      { subject: "[Airflow] DAG 'seller_gmv_daily_refresh' — Task 'hive_gmv_agg' failed: OOM — Java heap space", sender: "airflow-alerts@quickcart.in", tool: "Airflow" },
      { subject: "[Tableau] 'Seller GMV by Category' workbook: Vikram Das added a comment on Electronics slide", sender: "noreply@tableau.com", tool: "Tableau" },
      { subject: "[Tableau] Alert: Fashion category GMV down 14% WoW — below threshold", sender: "noreply@tableau.com", tool: "Tableau" },
      { subject: "[dbt Cloud] Job 'mart_seller_tier_features' failed — circular reference in seller_return_rate model", sender: "noreply@getdbt.com", tool: "dbt" },
      { subject: "[GitHub] PR review requested: feat/return-rate-attribution-v1 — new seller penalty score calculation", sender: "noreply@github.com", tool: "GitHub" },
      { subject: "[Jira] DATA-1892 assigned: BBD pre-analysis — undersupplied categories report needed by July 20", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[Confluence] Pooja Krishnan updated 'BBD 2024 Analytics Runbook' — new sections on Hive job scheduling and data freeze timelines", sender: "confluence@atlassian.net", tool: "Confluence" },
      { subject: "Zoom: Analytics Weekly — Fri 11:00 AM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "RE: Seller tier revamp — Meera wants the new tier scores for 50K electronics sellers by end of month", sender: "pooja.krishnan@quickcart.in" },
      { subject: "RE: BBD analysis — category heads meeting is July 22, not July 25. Can you pull forward?", sender: "vikram.das@quickcart.in" },
      { subject: "IT: Please verify your active Microsoft 365 licences in the IT portal before July 15", sender: "it@quickcart.in" },
      { subject: "QuickCart All-Hands July 2024 — CEO Q3 update, BBD preview, recording on intranet", sender: "allhands@quickcart.in" },
      { subject: "Your June expense claim of ₹9,800 has been approved — credit in next payroll", sender: "finance@quickcart.in" },
      { subject: "DataEngConf India 2024: Hive vs Spark migration patterns, real-time analytics at scale", sender: "noreply@dataengconf.in" },
    ],
    calendarPatterns: [
      { title: "Analytics Weekly", recurrence: "weekly", organizer: "Pooja Krishnan", attendees: ["analytics team"], videoLink: "zoom.us" },
      { title: "BBD Pre-analysis Review", recurrence: "weekly", organizer: "Arjun Shah", attendees: ["Pooja Krishnan", "Vikram Das", "Riya Malhotra"], videoLink: "zoom.us" },
      { title: "Category Head Briefing — BBD Readiness", recurrence: "monthly", organizer: "Pooja Krishnan", attendees: ["analytics + all category heads"], videoLink: "zoom.us" },
      { title: "BBD Analytics War Room", recurrence: "daily", organizer: "Pooja Krishnan", attendees: ["analytics team", "category heads"], videoLink: "zoom.us" },
      { title: "Data Platform Quarterly Review", recurrence: "quarterly", organizer: "Pooja Krishnan", attendees: ["analytics", "data eng", "infra"], videoLink: "zoom.us" },
      { title: "Seller Tier Model — Weekly Progress", recurrence: "weekly", organizer: "Arjun Shah", attendees: ["Meera Nair", "Pooja Krishnan"], videoLink: "meet.google.com" },
      { title: "Return Rate Taskforce Kickoff", recurrence: "biweekly", organizer: "Pooja Krishnan", attendees: ["Arjun Shah", "Neha Singh", "Vikram Das"], videoLink: "zoom.us" },
      { title: "Data x Category Head — BBD Prep", recurrence: "monthly", organizer: "Arjun Shah", attendees: ["all category analytics leads", "category heads"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "Airflow DAG for seller GMV crashed Monday with Java OOM on Hive — executor memory scaled but the pipeline ran 18 hours behind, putting the BBD readiness report at risk. Fashion GMV is down 14% WoW and will dominate the category heads briefing now due July 20. The Seller Tier Model revamp covers 1.2M sellers; Meera needs electronics tier scores by end-of-month but we're on the same Hive cluster so I need to stagger jobs with Neha or the aggregation pipeline misses again. Return rate is stuck at 8.3% — attribution analysis hasn't started yet because the Spark jobs are still backlogged from the OOM incident.",
  },
};

export const quickCartMarketing: CompanyProfile = {
  ...META,
  id: "quickcart-marketing",
  personaRole: "marketing",
  persona: {
    name: "Pooja Verma",
    role: "Marketing Manager — Category Campaigns",
    company: "QuickCart",
    tenure: "4 years",
    reportsTo: "Ashwin Rao (VP Marketing)",
    toolStack: ["Slack", "Google Ads", "Meta Ads", "Google Analytics", "AppsFlyer", "Salesforce Marketing Cloud", "Tableau", "Zoom", "Jira", "Canva"],
    primaryCommsTools: ["Slack", "Salesforce Marketing Cloud"],
    invisibleComms: ["WhatsApp (brand agency coordination)", "phone calls with Google & Meta account managers"],
    marketingTools: ["Google Ads", "Meta Ads", "Google Analytics", "AppsFlyer"],
    projects: [
      {
        name: "Big Billion Days 2024",
        codename: "Operation Dhamaka",
        status: "active",
        description: "₹180Cr marketing budget for QuickCart's biggest sale event. Lead planner for Electronics and Home categories — ₹60Cr allocation. 30-day countdown campaign: teaser → launch → post-sale. Coordinating 6 agencies.",
        tools: ["Google Ads", "Meta Ads", "Salesforce Marketing Cloud", "AppsFlyer"],
        keyPeople: ["Ashwin Rao", "6 agency leads"],
      },
      {
        name: "Loyalty Programme Relaunch",
        status: "planning",
        description: "QuickCart Plus has 4.2M subscribers but 38% are dormant (no purchase in 90 days). Designing the reactivation campaign and the new benefits structure to improve active subscriber rate from 62% to 80%.",
        tools: ["Salesforce Marketing Cloud", "Tableau", "Canva"],
        keyPeople: ["product team", "Ashwin Rao"],
      },
      {
        name: "Vernacular App Install Campaigns",
        status: "active",
        description: "Hindi, Tamil, and Telugu language install campaigns targeting Tier-2/3 users. Hindi campaign at ₹82 CPI (target ₹75). Tamil and Telugu launching Q3. Bulk of new user growth is coming from these markets.",
        tools: ["Google Ads", "Meta Ads", "AppsFlyer"],
        keyPeople: ["Ashwin Rao"],
      },
    ],
    collaborators: [
      { name: "Ashwin Rao", role: "VP Marketing", relationship: "manager", commsChannel: "Weekly 1:1 + Slack" },
      { name: "Arjun Shah", role: "Growth Analyst", relationship: "cross-functional", commsChannel: "Slack + Tableau shared dashboards" },
      { name: "Meera Nair", role: "Senior PM, Seller Platform", relationship: "cross-functional", commsChannel: "Monthly marketing x product sync" },
      { name: "Rahul agency lead", role: "Creative Agency Lead", relationship: "external", commsChannel: "Email + weekly creative review call" },
      { name: "Sunita CRM lead", role: "CRM & Retention Lead", relationship: "peer", commsChannel: "Slack #loyalty-programme + weekly sync" },
    ],
    emailPatterns: [
      { subject: "[Google Ads] BBD Electronics Campaign — Smart Shopping: ₹8.4Cr spend this week, ROAS 3.2x", sender: "googleads-noreply@google.com", tool: "Google Ads" },
      { subject: "[Google Ads] Recommendation: Increase BBD Home campaign budget by 40% — strong ROAS signal", sender: "googleads-noreply@google.com", tool: "Google Ads" },
      { subject: "[Meta for Business] BBD Teaser campaign: 48M impressions, 2.1% CTR — above benchmark for consideration phase", sender: "advertiser-noreply@meta.com", tool: "Meta Ads" },
      { subject: "[Meta Business Manager] Budget alert: BBD_Electronics_Retargeting reached ₹2Cr daily cap", sender: "noreply@facebookmail.com", tool: "Meta Ads" },
      { subject: "[Salesforce Marketing Cloud] Journey 'BBD 7-Day Countdown' — Day 5 email: 14.2M sent, 11.3% open, 3.8% CTR", sender: "noreply@salesforce.com", tool: "Salesforce Marketing Cloud" },
      { subject: "[Salesforce Marketing Cloud] QuickCart Plus reactivation segment ready: 1.6M dormant subscribers", sender: "noreply@salesforce.com", tool: "Salesforce Marketing Cloud" },
      { subject: "[AppsFlyer] BBD campaign attribution — App installs: 890K this week, CPI ₹82 for Hindi campaigns", sender: "noreply@appsflyer.com", tool: "AppsFlyer" },
      { subject: "[Google Analytics] BBD landing page: 4.2M sessions in 48 hours — server capacity alert from infra team", sender: "noreply@google.com", tool: "Google Analytics" },
      { subject: "[Tableau] 'BBD Marketing Dashboard' — Pooja Verma, daily report ready", sender: "noreply@tableau.com", tool: "Tableau" },
      { subject: "Zoom: BBD War Room — Daily 8:00 AM until event ends", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "[Jira] MKTG-2891 assigned: BBD Day-of creative approvals — agency uploads by 6 AM, you review by 8 AM", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "RE: Tamil/Telugu campaign launch delayed — translation agency needs 3 more days for QA", sender: "rahul.agency@digitalco.in" },
      { subject: "RE: BBD budget — Ashwin approved incremental ₹12Cr for Electronics in final 3 days, shift from Home", sender: "ashwin.rao@quickcart.in" },
      { subject: "IT: Please verify your active Microsoft 365 licences in the IT portal before July 15", sender: "it@quickcart.in" },
      { subject: "QuickCart All-Hands July 2024 — CEO Q3 update, BBD preview, recording on intranet", sender: "allhands@quickcart.in" },
      { subject: "Your June expense claim of ₹22,000 (BBD agency coordination) has been approved", sender: "finance@quickcart.in" },
      { subject: "MMA India: ecommerce campaign benchmarks — category-level ROAS, install costs, and attribution", sender: "insights@mmaglobal.com" },
    ],
    calendarPatterns: [
      { title: "BBD War Room — Daily standup", recurrence: "daily", organizer: "Ashwin Rao", attendees: ["all marketing"], videoLink: "zoom.us" },
      { title: "Agency Creative Review", recurrence: "weekly", organizer: "Pooja Verma", attendees: ["Pooja Verma", "Rahul agency lead", "design team"], videoLink: "zoom.us" },
      { title: "QuickCart Plus Loyalty Relaunch", recurrence: "biweekly", organizer: "Sunita CRM lead", attendees: ["Pooja Verma", "Sunita CRM lead", "product"], videoLink: "meet.google.com" },
      { title: "BBD Budget Realignment", recurrence: "biweekly", organizer: "Ashwin Rao", attendees: ["marketing leads", "finance"], videoLink: "zoom.us" },
      { title: "QuickCart All-Hands", recurrence: "monthly", organizer: "CEO office", attendees: ["all employees"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "BBD countdown is full-on. Ashwin shifted ₹12Cr from Home to Electronics based on ROAS signals — now I need to rebuild the media mix for Home with a smaller budget in 48 hours. The Tamil and Telugu campaigns are delayed 3 days by the translation agency which is going to hurt our Tier-2 install targets. Salesforce Marketing Cloud sent the Day 5 BBD countdown email to 14.2M users and open rate is at 11.3% which is above last year. The QuickCart Plus reactivation segment is ready — 1.6M dormant subscribers — but I can't run the reactivation campaign during BBD or it'll confuse the messaging, so it waits.",
  },
};
