// MediConnect — inspired by Practo (health tech, ~1,200 people, Bangalore)
import type { CompanyProfile } from "../types.js";

const META = {
  companyKey: "mediconnect",
  name: "MediConnect",
  industry: "Health Tech",
  stage: "Series D",
  size: "1,200 employees",
  city: "Bangalore",
  archetype: "B2C health tech",
};

export const mediConnectPM: CompanyProfile = {
  ...META,
  id: "mediconnect-pm",
  personaRole: "pm",
  persona: {
    name: "Aditya Kumar",
    role: "Product Manager — Consultation & Video",
    company: "MediConnect",
    tenure: "2 years 2 months",
    reportsTo: "Shruti Bose (Head of Product)",
    toolStack: ["Slack", "Jira", "Confluence", "Figma", "Mixpanel", "Zoom", "Notion", "Looker", "PagerDuty"],
    primaryCommsTools: ["Slack", "Jira"],
    invisibleComms: ["WhatsApp (doctor partner escalations)", "calls with key doctor accounts"],
    marketingTools: [],
    projects: [
      {
        name: "Video Consultation Reliability",
        codename: "Project Darpan",
        status: "active",
        description: "Video consultation completion rate is 71.4% — 28.6% drop due to connectivity failures, UI bugs, and doctor no-shows. Target 85% by Q3. Working on adaptive bitrate, retry logic, and doctor punctuality score.",
        tools: ["Jira", "PagerDuty", "Mixpanel", "Confluence"],
        keyPeople: ["Rahul Singh", "Shruti Bose"],
      },
      {
        name: "Prescription-to-Pharmacy Bridge",
        codename: "Project Setu",
        status: "planning",
        description: "34% of patients who receive a prescription after consultation fill it via MediConnect. Aiming for 55% by building a one-tap prescription forwarding to our pharmacy network at consultation end.",
        tools: ["Figma", "Jira", "Notion"],
        keyPeople: ["Meera Krishnan", "Aditya Kumar"],
      },
      {
        name: "Doctor NPS Recovery",
        status: "active",
        description: "Doctor NPS dropped from 52 to 38 after the new scheduling system launched. Root cause: appointment rescheduling notifications were going to the wrong phone number. Hotfix shipped; now doing NPS recovery programme.",
        tools: ["Jira", "Mixpanel"],
        keyPeople: ["Priya Nair"],
      },
    ],
    collaborators: [
      { name: "Shruti Bose", role: "Head of Product", relationship: "manager", commsChannel: "Weekly 1:1 + Slack" },
      { name: "Rahul Singh", role: "Engineering Lead, Consultation", relationship: "peer", commsChannel: "Slack #consultation-eng + Jira" },
      { name: "Meera Krishnan", role: "Pharmacy Product PM", relationship: "peer", commsChannel: "Slack + monthly alignment" },
      { name: "Priya Nair", role: "Doctor Success Manager", relationship: "cross-functional", commsChannel: "Slack + bi-weekly sync" },
      { name: "Dr Suresh Iyer", role: "Medical Advisory (part-time)", relationship: "external", commsChannel: "Email + quarterly review" },
    ],
    emailPatterns: [
      { subject: "[Jira] CONS-892 assigned to you: Implement adaptive bitrate for video SDK — WebRTC fallback", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[Jira] CONS-901: Doctor punctuality score algorithm — Shruti Bose added comment: 'Can we use calendar no-show data?'", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[PagerDuty] CRITICAL: video_consultation_failure_rate 34% for last 15 minutes — Karnataka region", sender: "noreply@pagerduty.com", tool: "PagerDuty" },
      { subject: "[Mixpanel] Alert: consultation_completion_rate dropped below 68% threshold — Aditya Kumar notified", sender: "alerts@mixpanel.com", tool: "Mixpanel" },
      { subject: "[Figma] Meera Krishnan shared 'Prescription Bridge — Handoff Flow v2' with you", sender: "noreply@figma.com", tool: "Figma" },
      { subject: "[Confluence] Rahul Singh updated 'Video Consultation — WebRTC Fallback Architecture'", sender: "confluence@atlassian.net", tool: "Confluence" },
      { subject: "[Notion] Shruti Bose shared 'H2 Product Roadmap — Consultation Pillar' with you", sender: "mail@mail.notion.so", tool: "Notion" },
      { subject: "Zoom: Product Weekly — Wed 11:00 AM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "RE: Doctor NPS recovery — 14 doctors replied to the outreach, 9 are open to feedback call", sender: "priya.nair@mediconnect.in" },
      { subject: "RE: Prescription bridge PRD — need pharmacy API SLAs before we commit to the Q3 timeline", sender: "meera.krishnan@mediconnect.in" },
    ],
    calendarPatterns: [
      { title: "Product Weekly", recurrence: "weekly", organizer: "Shruti Bose", attendees: ["all PMs"], videoLink: "zoom.us" },
      { title: "1:1 with Shruti", recurrence: "weekly", organizer: "Shruti Bose", attendees: ["Aditya Kumar"], videoLink: "zoom.us" },
      { title: "Consultation Sprint Review", recurrence: "biweekly", organizer: "Aditya Kumar", attendees: ["Rahul Singh", "Meera Krishnan"], videoLink: "meet.google.com" },
      { title: "Doctor Partner Monthly Review", recurrence: "monthly", organizer: "Priya Nair", attendees: ["Aditya Kumar", "Priya Nair", "Dr Suresh Iyer"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "Video reliability crisis on Monday — Karnataka had a 34% failure rate for 15 minutes, traced to a CDN edge node issue. Rahul had a fix in 40 minutes but doctor complaints are still coming in via Priya. NPS recovery programme is showing green: 9 of 14 doctors we reached out to are open to feedback calls, which is better than expected. Thursday: the Prescription Bridge PRD is blocked because we don't have the pharmacy API SLAs — Meera is chasing the pharmacy team. Shruti approved the adaptive bitrate approach for Project Darpan, so we unblocked that in planning this week.",
  },
};

export const mediConnectAnalyst: CompanyProfile = {
  ...META,
  id: "mediconnect-analyst",
  personaRole: "analyst",
  persona: {
    name: "Sneha Patel",
    role: "Data Analyst — Patient & Doctor Metrics",
    company: "MediConnect",
    tenure: "1 year 6 months",
    reportsTo: "Vivek Nair (Head of Data)",
    toolStack: ["Slack", "BigQuery", "dbt", "Looker", "Python", "Jupyter", "GitHub", "Jira", "Notion", "Zoom"],
    primaryCommsTools: ["Slack", "Looker"],
    invisibleComms: ["WhatsApp (data team quick pings)"],
    marketingTools: [],
    projects: [
      {
        name: "Doctor Utilisation Model",
        status: "active",
        description: "Predict which doctors are underutilised (< 50% slot fill rate) and trigger marketplace recommendations to boost demand. Current slot fill rate: 61% across the platform, target 75%.",
        tools: ["BigQuery", "Python", "Looker"],
        keyPeople: ["Vivek Nair", "Priya Nair"],
      },
      {
        name: "Patient LTV Framework",
        status: "active",
        description: "Build a 12-month LTV model for patient cohorts by acquisition channel and first-consultation specialty. Hypothesis: patients acquired through corporate tie-ups have 3x LTV vs app-store organic.",
        tools: ["dbt", "BigQuery", "Looker"],
        keyPeople: ["Aditya Kumar", "marketing team"],
      },
      {
        name: "HIPAA-Compliant Reporting Layer",
        status: "planning",
        description: "Current analytics queries run on raw patient data in BigQuery. Need a PII-masked reporting layer before we can give analysts broader access. Legal has been asking for 6 months.",
        tools: ["dbt", "BigQuery"],
        keyPeople: ["Vivek Nair"],
      },
    ],
    collaborators: [
      { name: "Vivek Nair", role: "Head of Data", relationship: "manager", commsChannel: "Daily check-in + Slack" },
      { name: "Aditya Kumar", role: "PM, Consultation", relationship: "cross-functional", commsChannel: "Slack + bi-weekly analytics sync" },
      { name: "Priya Nair", role: "Doctor Success Manager", relationship: "cross-functional", commsChannel: "Slack + shared Looker dashboards" },
      { name: "Rohan Mehta", role: "Data Engineer", relationship: "peer", commsChannel: "GitHub + Slack #data-eng" },
      { name: "Arjun Dixit", role: "Marketing Analyst", relationship: "peer", commsChannel: "Slack + shared dbt workspace" },
    ],
    emailPatterns: [
      { subject: "[dbt Cloud] Job 'mart_doctor_utilisation_daily' — 3 tests failed: unique constraint on doctor_slot_id", sender: "noreply@getdbt.com", tool: "dbt" },
      { subject: "[Looker] 'Doctor Utilisation Dashboard' — Priya Nair has a question on the slot_fill_rate metric definition", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "[Looker] Alert: National patient NPS dropped to 38 — below 40 threshold for the first time this year", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "[GitHub] PR review requested: feat/patient-ltv-cohort-model — adds acquisition_channel dimension", sender: "noreply@github.com", tool: "GitHub" },
      { subject: "[BigQuery] Scheduled query 'daily_consultation_funnel' exceeded quota — 14.2TB scanned", sender: "noreply@google.com", tool: "BigQuery" },
      { subject: "[Jira] DATA-112 assigned to you: Patient LTV by acquisition channel — needed for H2 planning deck", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "Zoom: Data Team Weekly — Mon 9:30 AM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "RE: Patient LTV model — marketing team needs the corporate vs organic split by Friday", sender: "arjun.dixit@mediconnect.in" },
      { subject: "RE: HIPAA reporting layer — legal escalated to CEO, now it's a Q3 blocker", sender: "vivek.nair@mediconnect.in" },
    ],
    calendarPatterns: [
      { title: "Data Team Weekly", recurrence: "weekly", organizer: "Vivek Nair", attendees: ["Sneha Patel", "Rohan Mehta", "Arjun Dixit"], videoLink: "zoom.us" },
      { title: "Analytics x PM Sync", recurrence: "biweekly", organizer: "Aditya Kumar", attendees: ["Sneha Patel", "Aditya Kumar"], videoLink: "meet.google.com" },
      { title: "HIPAA Compliance Review", recurrence: "monthly", organizer: "Vivek Nair", attendees: ["data team", "legal"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "The HIPAA reporting layer got escalated to CEO level on Wednesday — legal is saying it's now a Q3 blocker not just a nice-to-have. That means it jumps Vivek's priority stack and I'll need to pause the LTV model. Marketing also needs the corporate-vs-organic patient LTV split by Friday for the H2 planning deck — that analysis is straightforward in BigQuery but the slot utilisation model has a dbt test failure that's been blocking me since Monday. Doctor NPS dropping to 38 is a big story; I need to figure out if the scheduling notification bug caused patients to cancel, or if something else changed.",
  },
};

export const mediConnectMarketing: CompanyProfile = {
  ...META,
  id: "mediconnect-marketing",
  personaRole: "marketing",
  persona: {
    name: "Nikhil Gupta",
    role: "Marketing Manager — Patient Acquisition",
    company: "MediConnect",
    tenure: "2 years 8 months",
    reportsTo: "Deepa Verma (VP Marketing)",
    toolStack: ["Slack", "Google Ads", "Meta Ads", "Google Analytics", "HubSpot", "Klaviyo", "SEMrush", "Looker", "Zoom", "Jira"],
    primaryCommsTools: ["Slack", "HubSpot"],
    invisibleComms: ["calls with corporate HR partners", "WhatsApp (insurance broker network)"],
    marketingTools: ["Google Ads", "Meta Ads", "Google Analytics", "HubSpot"],
    projects: [
      {
        name: "Corporate Health Package Sales",
        status: "active",
        description: "Close 8 new corporate health package deals by Q3-end (currently at 3/8). Pipeline: 14 companies in HubSpot at various stages. Average deal size: ₹18L/year. Key blocker: procurement approvals taking 6-8 weeks.",
        tools: ["HubSpot", "Google Ads", "Zoom"],
        keyPeople: ["Deepa Verma", "corporate sales team"],
      },
      {
        name: "SEO Content Programme",
        status: "active",
        description: "Medical content SEO: ranking for 'symptoms of X' and 'best doctor for Y' queries. Currently 2.3M organic sessions/month, target 4M by Q4. Working with a team of 8 freelance medical writers.",
        tools: ["SEMrush", "Google Analytics", "Klaviyo"],
        keyPeople: ["Arjun content lead"],
      },
      {
        name: "Referral Doctor Programme",
        status: "planning",
        description: "Incentivise partner clinics to refer patients to MediConnect for specialist consultations — revenue share model. Potentially 20K incremental consultations/month at near-zero CAC.",
        tools: ["HubSpot", "Notion"],
        keyPeople: ["Priya Nair", "Deepa Verma"],
      },
    ],
    collaborators: [
      { name: "Deepa Verma", role: "VP Marketing", relationship: "manager", commsChannel: "Weekly 1:1 + Slack" },
      { name: "Aditya Kumar", role: "PM, Consultation", relationship: "cross-functional", commsChannel: "Monthly product-marketing sync" },
      { name: "Sneha Patel", role: "Data Analyst", relationship: "cross-functional", commsChannel: "Slack + Looker" },
      { name: "Priya Nair", role: "Doctor Success Manager", relationship: "cross-functional", commsChannel: "Slack + referral programme sync" },
      { name: "Rohan content lead", role: "Content & SEO Lead", relationship: "peer", commsChannel: "Slack #seo-content + weekly" },
    ],
    emailPatterns: [
      { subject: "[Google Ads] Campaign 'MediConnect_Specialist_Search_South' — weekly performance: 2,400 clicks, CPC ₹38, 340 consultation bookings", sender: "googleads-noreply@google.com", tool: "Google Ads" },
      { subject: "[Google Ads] Smart bidding alert: 'Doctor Appointment' campaign ROAS dropped 18% — review recommended", sender: "googleads-noreply@google.com", tool: "Google Ads" },
      { subject: "[Meta for Business] Ad 'MediConnect_Diabetes_Specialist_Hindi' delivery: 1.2M reach, 0.8% CTR", sender: "advertiser-noreply@meta.com", tool: "Meta Ads" },
      { subject: "[HubSpot] Deal 'Infosys Corporate Health — 2,500 employees' moved to Proposal stage", sender: "notifications@hubspot.com", tool: "HubSpot" },
      { subject: "[HubSpot] Deal 'Wipro Wellness Package' — last activity was 14 days ago. Follow up?", sender: "notifications@hubspot.com", tool: "HubSpot" },
      { subject: "[HubSpot] New inbound lead: TCS Benefits Team — interested in corporate package", sender: "notifications@hubspot.com", tool: "HubSpot" },
      { subject: "[SEMrush] Weekly organic report: 'symptoms of dengue' ranking moved from #4 to #2", sender: "noreply@semrush.com", tool: "SEMrush" },
      { subject: "[SEMrush] Competitor alert: Practo added 34 new pages targeting 'online doctor consultation' this week", sender: "noreply@semrush.com", tool: "SEMrush" },
      { subject: "[Google Analytics] Organic search: 2.3M sessions this week, +12% WoW — 'dengue symptoms' article driving spike", sender: "noreply@google.com", tool: "Google Analytics" },
      { subject: "[Klaviyo] Email nurture 'Corporate Health — Decision Maker Sequence' Step 4: 14.2% open rate", sender: "noreply@klaviyo.com", tool: "Klaviyo" },
      { subject: "[Looker] 'Marketing Attribution Dashboard' — scheduled delivery to nikhil.gupta@mediconnect.in", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "Zoom: Marketing Weekly — Tue 10:00 AM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "RE: Infosys deal — procurement team wants a pilot with 100 employees before full rollout", sender: "deepa.verma@mediconnect.in" },
      { subject: "RE: SEO content — 8 freelancers submitted dengue/monsoon season articles, need your review by Thursday", sender: "rohan@mediconnect.in" },
    ],
    calendarPatterns: [
      { title: "Marketing Weekly", recurrence: "weekly", organizer: "Deepa Verma", attendees: ["Nikhil Gupta", "Rohan content lead"], videoLink: "zoom.us" },
      { title: "Corporate Sales Deals Review", recurrence: "weekly", organizer: "Nikhil Gupta", attendees: ["Nikhil Gupta", "Deepa Verma", "sales team"], videoLink: "meet.google.com" },
      { title: "Product x Marketing Monthly", recurrence: "monthly", organizer: "Deepa Verma", attendees: ["all marketing", "Aditya Kumar"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "The Infosys deal moved to proposal stage on Monday but now procurement wants a 100-person pilot — that's a 6-week delay. Still the biggest deal in the pipeline at ₹18L, so I can't walk away. The monsoon illness content spike is real: our 'dengue symptoms' article jumped to #2 on Google this week, driving 12% organic growth. I spent Thursday reviewing the 8 freelancer articles for the content calendar. HubSpot pipeline looks healthy on top-of-funnel but deal velocity is slow — 4 deals have had zero activity in 14+ days and I need to either re-engage or disqualify them before Deepa's Q3 review.",
  },
};
