// FeastRunner — inspired by Swiggy (food delivery / quick commerce, ~5,500 people, Bangalore)
import type { CompanyProfile } from "../types.js";

const META = {
  companyKey: "feastrunner",
  name: "FeastRunner",
  industry: "Food Tech / Quick Commerce",
  stage: "Late Stage / Pre-IPO",
  size: "5,500 employees",
  city: "Bangalore",
  archetype: "B2C food tech",
};

// ── PM: Priya Sharma ─────────────────────────────────────────────────────────
export const feastRunnerPM: CompanyProfile = {
  ...META,
  id: "feastrunner-pm",
  personaRole: "pm",
  persona: {
    name: "Priya Sharma",
    role: "Senior Product Manager — Order Experience",
    company: "FeastRunner",
    tenure: "2 years 8 months",
    reportsTo: "Arjun Kapoor (VP Product, Growth)",
    toolStack: ["Slack", "Linear", "Notion", "Figma", "Mixpanel", "Amplitude", "Zoom", "Looker", "PagerDuty", "Confluence", "Google Sheets"],
    primaryCommsTools: ["Slack", "Linear"],
    invisibleComms: ["WhatsApp (cross-team quick syncs)", "in-person whiteboard sessions"],
    marketingTools: [],
    projects: [
      {
        name: "Checkout Completion",
        codename: "Project Dhruv",
        status: "active",
        description: "Reduce checkout drop-off rate from 31.2% to <20% by Q3-end. Core hypothesis: OTP friction and payment method fatigue are the two biggest levers.",
        tools: ["Linear", "Figma", "Amplitude", "Mixpanel", "Notion"],
        keyPeople: ["Arjun Kapoor", "Deepika Rao", "Rahul Mishra"],
      },
      {
        name: "Restaurant Health Score",
        codename: "Project Netra",
        status: "active",
        description: "Build an ML-driven health score for 85,000 restaurant partners to predict churn 30 days in advance and trigger proactive account management.",
        tools: ["Notion", "Linear", "Looker"],
        keyPeople: ["Suresh Nair", "Aditya Bhat"],
      },
      {
        name: "Reorder Flow Simplification",
        status: "winding-down",
        description: "Shipped the single-tap reorder feature in Sprint 42. Now in post-launch monitoring — reorder rate up 4.1 points WoW. Writing the retrospective.",
        tools: ["Mixpanel", "Linear"],
        keyPeople: ["Deepika Rao"],
      },
    ],
    collaborators: [
      { name: "Arjun Kapoor", role: "VP Product, Growth", relationship: "manager", commsChannel: "Weekly 1:1 on Zoom + Slack async" },
      { name: "Deepika Rao", role: "Senior Designer", relationship: "peer", commsChannel: "Figma comments + Slack #product-design" },
      { name: "Rahul Mishra", role: "Data Analyst, Growth", relationship: "cross-functional", commsChannel: "Slack DMs + shared Looker dashboards" },
      { name: "Suresh Nair", role: "Engineering Lead, Checkout", relationship: "peer", commsChannel: "Slack #checkout-eng + Linear" },
      { name: "Kavita Menon", role: "Product Marketing", relationship: "cross-functional", commsChannel: "Slack + bi-weekly sync" },
    ],
    emailPatterns: [
      { subject: "[Linear] Arjun assigned you #CHECKOUT-892: Implement single-click reorder for saved address", sender: "notify@linear.app", tool: "Linear" },
      { subject: "[Linear] Sprint 43 planning: 4 issues need estimation by Thursday 5pm", sender: "notify@linear.app", tool: "Linear" },
      { subject: "[Linear] #CHECKOUT-901 moved to Done: Fix OTP retry race condition", sender: "notify@linear.app", tool: "Linear" },
      { subject: "[Linear] #NETRA-12: Restaurant churn prediction model — Priya Sharma added a comment", sender: "notify@linear.app", tool: "Linear" },
      { subject: "[Mixpanel] Weekly Digest — Order Funnel: checkout_initiated→order_placed dropped 3.2pp WoW", sender: "digest@mixpanel.com", tool: "Mixpanel" },
      { subject: "[Mixpanel] Alert: payment_failure_rate exceeded threshold (>8%) for last 2 hours", sender: "alerts@mixpanel.com", tool: "Mixpanel" },
      { subject: "[Amplitude] Experiment 'Simplified Checkout v3' reached significance — p=0.03, +2.8% conversion", sender: "noreply@amplitude.com", tool: "Amplitude" },
      { subject: "[Amplitude] New experiment created: 'OTP-less checkout for saved users' — review cohort definition", sender: "noreply@amplitude.com", tool: "Amplitude" },
      { subject: "[Figma] Deepika Rao commented on 'Reorder Flow — Iteration 6': 'The empty state copy needs work'", sender: "noreply@figma.com", tool: "Figma" },
      { subject: "[Figma] Deepika shared 'Restaurant Page Redesign — v4' with you", sender: "noreply@figma.com", tool: "Figma" },
      { subject: "[Notion] Rahul Mishra edited 'Q3 OKR: Checkout Completion Rate — Mid-Cycle Review'", sender: "mail@mail.notion.so", tool: "Notion" },
      { subject: "[Notion] You were mentioned in 'Restaurant Health Score PRD — v2' by Suresh Nair", sender: "mail@mail.notion.so", tool: "Notion" },
      { subject: "[PagerDuty] CRITICAL [SEV-1]: checkout_service error rate 14.3% — Assigned to Priya Sharma", sender: "noreply@pagerduty.com", tool: "PagerDuty" },
      { subject: "[PagerDuty] RESOLVED: checkout_service error rate back to baseline", sender: "noreply@pagerduty.com", tool: "PagerDuty" },
      { subject: "[Looker] Scheduled report: 'Daily Order Funnel by City' — delivered to priya.sharma@feastrunner.in", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "[Looker] Rahul Mishra shared 'Checkout Abandonment Deep Dive — July 2024' with you", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "Zoom Meeting Starting: Growth Product Weekly — Thu 3:00 PM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "RE: Q3 OKR Mid-Cycle Check-in — Checkout team needs to close 12pp in 6 weeks", sender: "arjun.kapoor@feastrunner.in" },
      { subject: "RE: Project Dhruv — A/B test variant B approval needed before Friday launch", sender: "deepika.rao@feastrunner.in" },
      { subject: "Action required: Sprint 43 retrospective notes — please add your items", sender: "suresh.nair@feastrunner.in" },
      { subject: "[Confluence] Suresh updated 'Checkout Service Architecture — v3': added payment gateway fallback design", sender: "confluence@atlassian.net", tool: "Confluence" },
      { subject: "Slack digest: 42 unread messages — #product-growth, #checkout-team, #incidents", sender: "feedback@slack.com", tool: "Slack" },
    ],
    calendarPatterns: [
      { title: "Growth Product Weekly", recurrence: "weekly", organizer: "Arjun Kapoor", attendees: ["Priya Sharma", "Kavita Menon", "Suresh Nair", "Rahul Mishra"], videoLink: "zoom.us" },
      { title: "1:1 with Arjun", recurrence: "weekly", organizer: "Arjun Kapoor", attendees: ["Priya Sharma"], videoLink: "zoom.us" },
      { title: "Sprint Planning — Checkout Team", recurrence: "biweekly", organizer: "Priya Sharma", attendees: ["Suresh Nair", "Deepika Rao", "Rahul Mishra", "checkout-eng"], videoLink: "zoom.us" },
      { title: "Design Review: Project Dhruv", recurrence: "weekly", organizer: "Priya Sharma", attendees: ["Deepika Rao", "Suresh Nair"], videoLink: "meet.google.com" },
      { title: "Q3 OKR Review — All PMs", recurrence: "monthly", organizer: "Arjun Kapoor", attendees: ["all-pm-team"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "Monday was a war room — checkout completion dropped 4.3 points after the new payment gateway rollout, specifically in tier-2 cities. Suresh and I debugged until midnight; turned out to be a race condition in the OTP verification microservice when the fallback gateway kicks in. Hotfix went live Tuesday evening. Wednesday was the Q3 OKR mid-cycle review with Arjun — we're at 68% on the checkout completion OKR, need to close 12 points in 6 weeks which is tight. Project Netra got its first ML model run on Thursday; the precision at 0.73 is not enough to ship to account managers yet, Suresh wants 0.85 before we trust it in production.",
  },
};

// ── Analyst: Rahul Mishra ────────────────────────────────────────────────────
export const feastRunnerAnalyst: CompanyProfile = {
  ...META,
  id: "feastrunner-analyst",
  personaRole: "analyst",
  persona: {
    name: "Rahul Mishra",
    role: "Growth Analyst — Order Funnel & Retention",
    company: "FeastRunner",
    tenure: "1 year 4 months",
    reportsTo: "Aditya Bhat (Head of Data, Growth)",
    toolStack: ["Slack", "BigQuery", "dbt", "Looker", "Metabase", "Airflow", "Python", "GitHub", "Jira", "Notion", "Zoom"],
    primaryCommsTools: ["Slack", "BigQuery"],
    invisibleComms: ["WhatsApp (data team group)", "verbal standup walkups"],
    marketingTools: [],
    projects: [
      {
        name: "Retention Cohort Framework",
        codename: "Project Kavach",
        status: "active",
        description: "Build D7/D30/D90 retention cohorts in dbt that slice by acquisition channel, city tier, restaurant category, and device. Currently blocked on BigQuery memory — the 90-day join is hitting 12TB scans.",
        tools: ["BigQuery", "dbt", "Looker", "GitHub"],
        keyPeople: ["Aditya Bhat", "Nikhil Desai"],
      },
      {
        name: "City-wise Unit Economics",
        status: "active",
        description: "Model profitability per order by city, factoring in delivery cost, discount burn, and restaurant margin. Metros vs tier-2 story is critical for the IPO narrative.",
        tools: ["BigQuery", "Python", "Metabase"],
        keyPeople: ["Vikram Gupta", "Aditya Bhat"],
      },
      {
        name: "Instamart Adoption Analysis",
        status: "planning",
        description: "Deep-dive into quick commerce adoption: who uses both food + Instamart, what triggers the first Instamart order, and what's the LTV lift from dual-category users.",
        tools: ["BigQuery", "dbt", "Looker"],
        keyPeople: ["Priya Sharma"],
      },
    ],
    collaborators: [
      { name: "Aditya Bhat", role: "Head of Data, Growth", relationship: "manager", commsChannel: "Daily standup + Slack" },
      { name: "Priya Sharma", role: "Senior PM, Order Experience", relationship: "cross-functional", commsChannel: "Slack DMs + data requests via Jira" },
      { name: "Nikhil Desai", role: "Data Engineer", relationship: "peer", commsChannel: "GitHub PRs + Slack #data-eng" },
      { name: "Vikram Gupta", role: "Finance Analytics Lead", relationship: "cross-functional", commsChannel: "Slack + shared Metabase" },
      { name: "Kavita Menon", role: "Product Marketing", relationship: "cross-functional", commsChannel: "Slack + ad-hoc analysis requests" },
    ],
    emailPatterns: [
      { subject: "[dbt Cloud] Job 'mart_order_funnel_daily' failed — 2 tests failed: not_null on order_id", sender: "noreply@getdbt.com", tool: "dbt" },
      { subject: "[dbt Cloud] Documentation updated: mart_user_retention_cohort_v2 is now production", sender: "noreply@getdbt.com", tool: "dbt" },
      { subject: "[dbt Cloud] Run completed: growth_metrics_hourly — 847 models built in 4m 12s", sender: "noreply@getdbt.com", tool: "dbt" },
      { subject: "[Airflow] DAG 'daily_cohort_metrics_pipeline' failed — Task 'bq_export_cohort' returned exit code 1", sender: "airflow-alerts@feastrunner.in", tool: "Airflow" },
      { subject: "[Airflow] DAG 'instamart_adoption_etl' succeeded — next run: 2024-07-15 02:00 UTC", sender: "airflow-alerts@feastrunner.in", tool: "Airflow" },
      { subject: "[Looker] 'Weekly Growth Dashboard' — Scheduled delivery to rahul.mishra@feastrunner.in", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "[Looker] Priya Sharma shared 'Checkout Abandonment Deep Dive' with you", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "[Looker] Alert: 'Mumbai D7 Retention' dropped below 26% threshold", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "[Metabase] Question 'CAC by Acquisition Channel — June' updated by Vikram Gupta", sender: "notification@metabase.com", tool: "Metabase" },
      { subject: "[Metabase] Alert: 'Daily Orders by City Tier' — Tier-2 down 11% vs last Tuesday", sender: "notification@metabase.com", tool: "Metabase" },
      { subject: "[GitHub] PR review requested: feat/mart-order-funnel-v3 — added city_tier dimension", sender: "noreply@github.com", tool: "GitHub" },
      { subject: "[GitHub] Nikhil Desai merged your PR: fix/retention-cohort-null-handling", sender: "noreply@github.com", tool: "GitHub" },
      { subject: "[Jira] DATA-892 assigned to you: Build retention cohort segmented by restaurant category", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[Jira] DATA-901: City-wise unit economics model — Aditya Bhat added a comment", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "[Notion] Aditya Bhat shared 'Data Team Q3 Roadmap' with you", sender: "mail@mail.notion.so", tool: "Notion" },
      { subject: "Zoom: Data Weekly Stand-up — Mon 10:00 AM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "Slack digest: 67 unread — #data-eng, #analytics-requests, #growth-pm", sender: "feedback@slack.com", tool: "Slack" },
      { subject: "RE: Urgent data request — reorder rate by restaurant category for Q3 review (need by EOD)", sender: "priya.sharma@feastrunner.in" },
      { subject: "RE: June cohort D7 retention drop — potential tracking issue in new onboarding flow?", sender: "aditya.bhat@feastrunner.in" },
      { subject: "Quick question: what's our contribution margin per order for Instamart in Pune?", sender: "vikram.gupta@feastrunner.in" },
    ],
    calendarPatterns: [
      { title: "Data Team Weekly Stand-up", recurrence: "weekly", organizer: "Aditya Bhat", attendees: ["Rahul Mishra", "Nikhil Desai", "Vikram Gupta"], videoLink: "zoom.us" },
      { title: "Analyst Office Hours — open slot for PM requests", recurrence: "weekly", organizer: "Rahul Mishra", attendees: ["any PM"], videoLink: "meet.google.com" },
      { title: "BigQuery Cost Review", recurrence: "monthly", organizer: "Nikhil Desai", attendees: ["data-eng team"], videoLink: "meet.google.com" },
      { title: "Growth Analytics Review with Priya", recurrence: "biweekly", organizer: "Priya Sharma", attendees: ["Rahul Mishra", "Priya Sharma"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "The retention cohort framework hit a memory wall — the 90-day BigQuery join is scanning 12TB per run and timing out. Spent Monday-Tuesday with Nikhil partitioning the base tables by date, but the improvement wasn't enough; we're now exploring materialising an intermediate table. Meanwhile Priya had an urgent request for checkout team's Q3 review: reorder rate broken down by restaurant category. That ate Wednesday and Thursday. Separate signal issue: D7 retention for the June cohort is 28.3% versus 31.2% the month before — I'm 60% sure it's a tracking bug from the new onboarding flow, flagging to Aditya today.",
  },
};

// ── Marketing: Kavita Menon ──────────────────────────────────────────────────
export const feastRunnerMarketing: CompanyProfile = {
  ...META,
  id: "feastrunner-marketing",
  personaRole: "marketing",
  persona: {
    name: "Kavita Menon",
    role: "Performance Marketing Manager — User Acquisition",
    company: "FeastRunner",
    tenure: "3 years 1 month",
    reportsTo: "Rohan Pillai (VP Marketing)",
    toolStack: ["Slack", "Google Ads", "Meta Ads", "AppsFlyer", "CleverTap", "Klaviyo", "Google Analytics", "Looker", "Zoom", "Jira", "Canva"],
    primaryCommsTools: ["Slack", "Google Ads"],
    invisibleComms: ["WhatsApp (agency coordination)", "phone calls with Google & Meta reps"],
    marketingTools: ["Google Ads", "Meta Ads", "Google Analytics", "AppsFlyer"],
    projects: [
      {
        name: "Diwali Campaign 2024",
        codename: "Project Utsav",
        status: "planning",
        description: "₹12Cr multi-channel campaign for Diwali peak. Channel split: Google 40%, Meta 35%, CTV 15%, influencer 10%. Target: 2.8M incremental orders in the 10-day peak window.",
        tools: ["Google Ads", "Meta Ads", "CleverTap", "Klaviyo", "AppsFlyer"],
        keyPeople: ["Rohan Pillai", "Sunita Krishnan"],
      },
      {
        name: "Win-back: 30-Day Churned Users",
        status: "active",
        description: "Re-engage 4.1M users who haven't ordered in 30 days. Week 2 of the campaign — push + email + paid retargeting. Current reinstall rate 4.2% vs 2.8% benchmark.",
        tools: ["CleverTap", "Klaviyo", "Meta Ads", "AppsFlyer"],
        keyPeople: ["Sunita Krishnan"],
      },
      {
        name: "Organic App Install Growth",
        status: "active",
        description: "Reduce blended CAC by 15% through organic channels: ASO, referral programme optimisation, and social-first content. Target: organic share from 19% to 28% by Q4.",
        tools: ["Google Analytics", "AppsFlyer", "Canva"],
        keyPeople: ["Priya Sharma"],
      },
    ],
    collaborators: [
      { name: "Rohan Pillai", role: "VP Marketing", relationship: "manager", commsChannel: "Weekly 1:1 + Slack" },
      { name: "Sunita Krishnan", role: "CRM & Retention Marketing Lead", relationship: "peer", commsChannel: "Slack #crm-marketing + weekly sync" },
      { name: "Priya Sharma", role: "Senior PM, Order Experience", relationship: "cross-functional", commsChannel: "Slack + monthly alignment meeting" },
      { name: "Rahul Mishra", role: "Growth Analyst", relationship: "cross-functional", commsChannel: "Slack DMs + Looker dashboards" },
      { name: "Vikram Joshi", role: "External Agency Lead (digital)", relationship: "external", commsChannel: "Email + weekly review call" },
    ],
    emailPatterns: [
      { subject: "[Google Ads] Alert: Campaign 'Bangalore_FoodApp_SearchBrand_Q3' daily budget depleted — paused at 4:32 PM", sender: "googleads-noreply@google.com", tool: "Google Ads" },
      { subject: "[Google Ads] Your Performance Max campaign 'FeastRunner_App_Installs_India' weekly performance report", sender: "googleads-noreply@google.com", tool: "Google Ads" },
      { subject: "[Google Ads] Recommendation: Add 12 new keywords to 'Competitor_Keywords_South' — estimated +320 weekly clicks", sender: "googleads-noreply@google.com", tool: "Google Ads" },
      { subject: "[Meta for Business] Ad set 'Lookalike_30D_Purchasers_Hindi' has reached your ₹2L spend threshold", sender: "advertiser-noreply@meta.com", tool: "Meta Ads" },
      { subject: "[Meta Business Manager] Your ad 'Reorder_Feature_Tamil_Creative_v3' is now active", sender: "noreply@facebookmail.com", tool: "Meta Ads" },
      { subject: "[Meta] Ad rejected: 'Win-back_Churned_30D_English' — does not comply with financial services policy", sender: "noreply@facebookmail.com", tool: "Meta Ads" },
      { subject: "[AppsFlyer] Install attribution report — Week of July 8: Google UAC 41%, Meta 27%, Organic 19%, Referral 13%", sender: "noreply@appsflyer.com", tool: "AppsFlyer" },
      { subject: "[AppsFlyer] Fraud alert: Unusual install spike from publisher ID 84821 — review recommended", sender: "noreply@appsflyer.com", tool: "AppsFlyer" },
      { subject: "[CleverTap] Push campaign 'Weekend_Hungry_Push_Tier2' delivered: 4.1M users, 5.8% open rate, 2.3% conversion", sender: "noreply@clevertap.com", tool: "CleverTap" },
      { subject: "[CleverTap] Segment 'Churned_Premium_Users_30D' ready — 890K users, avg. LTV ₹4,200", sender: "noreply@clevertap.com", tool: "CleverTap" },
      { subject: "[CleverTap] Journey 'Win-back Flow v2' — Step 3 (push) has 3.1% CTR vs 5.8% last month. Investigate?", sender: "noreply@clevertap.com", tool: "CleverTap" },
      { subject: "[Klaviyo] Email campaign 'June_Reactivation_Inactive14D' sent to 2.3M — open rate 8.3%, CTR 1.1%", sender: "noreply@klaviyo.com", tool: "Klaviyo" },
      { subject: "[Klaviyo] Flow 'Post-First-Order Nurture' A/B test: Variant B (personalised cuisine rec) +2.1pp CTR", sender: "noreply@klaviyo.com", tool: "Klaviyo" },
      { subject: "[Google Analytics] Organic traffic spike: 'food delivery near me' driving 18K sessions this week", sender: "noreply@google.com", tool: "Google Analytics" },
      { subject: "[Looker] 'Marketing CAC Dashboard' — Kavita Menon, your weekly report is ready", sender: "noreply@looker.com", tool: "Looker" },
      { subject: "Zoom Meeting Starting: Marketing Weekly — Mon 11:00 AM", sender: "no-reply@zoom.us", tool: "Zoom" },
      { subject: "[Jira] MKTG-445 assigned to you: Set up Diwali 2024 tracking taxonomy in AppsFlyer before Aug 15", sender: "jira@atlassian.com", tool: "Jira" },
      { subject: "RE: Q4 Campaign Calendar — need your sign-off on Diwali budget split by EOD Friday", sender: "rohan.pillai@feastrunner.in" },
      { subject: "Budget approval required: ₹45L incremental spend for Durga Puja push campaign — 3 days left to approve", sender: "finance@feastrunner.in" },
      { subject: "RE: Google rep call recap — Performance Max optimisation + new video ad formats for Q4", sender: "vikram.joshi@digitalagency.in" },
    ],
    calendarPatterns: [
      { title: "Marketing Weekly Standup", recurrence: "weekly", organizer: "Rohan Pillai", attendees: ["Kavita Menon", "Sunita Krishnan", "content team"], videoLink: "zoom.us" },
      { title: "Google Ads Optimisation Review", recurrence: "biweekly", organizer: "Kavita Menon", attendees: ["Kavita Menon", "Vikram Joshi"], videoLink: "meet.google.com" },
      { title: "CRM x Paid Sync — Win-back campaign", recurrence: "weekly", organizer: "Sunita Krishnan", attendees: ["Kavita Menon", "Sunita Krishnan"], videoLink: "meet.google.com" },
      { title: "Diwali Campaign Kickoff", recurrence: "weekly", organizer: "Rohan Pillai", attendees: ["all marketing"], videoLink: "zoom.us" },
    ],
    weekNarrativeSeed: "Big week — Diwali campaign brief got CMO sign-off on Monday, ₹12Cr across channels. Started Google Ads structure Tuesday but the Performance Max setup is taking longer than expected — the asset groups for regional languages are a mess. The win-back campaign (30-day churned users) went live Wednesday: early reinstall rate at 4.2% which is beating our 2.8% benchmark, though Meta rejected the financial services-adjacent creative so we had to pivot to a food-first angle. CleverTap push CTR has dropped to 3.1% this week from 5.8% last month; my hypothesis is notification fatigue from the Instamart cross-sell blitz we ran last week — need Rahul's cohort data to confirm.",
  },
};
